### ISSUE TITLE
Design broken in certain android versions

### ISSUE THREAD

**Issue by prasanthsd** [sskhandek/react-native-emoji-input#47]
Hi,

When I use this library on android 6.0 and 7.0 the design of the smiley keyboard is broken. In 7.1 and above it works great. Any hints on how to solve this?

<a href="https://ibb.co/n6vRbyQ"><img src="https://i.ibb.co/CmZWzyV/Screenshot-1592547227.png" alt="Screenshot-1592547227" border="0" /></a>

**Comment by rijn** [comment]
Old android version doesn't support all composed emoji. You can follow the [readme](https://github.com/sskhandek/react-native-emoji-input#missing-emojis-on-some-devices) and filter the unsupport emojis. I won't suggest to use image view to support new emoji on legacy devices since it won't work in your text input and it will have huge impact on performance.

**Comment by xeroe** [comment]
Had the same problem on older android version.
Issue was, that some combined emojis use multiple chars when not supporting and ruining layout.

I filtered them out using



` 
 filterFunctionByUnicode = (emoji) => {
    return (
      (emoji.lib.added_in === "6.0" || emoji.lib.added_in === "6.1") &&
      emoji.char.length < 3
    );
  };
`
`
          <EmojiInput         
            filterFunctions={[this.filterFunctionByUnicode]}
          />
`
